# Generated by Django 3.1.4 on 2021-01-07 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, default='未分類', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
